<?php
/**
* Copyright © 2020 Roma Technology Limited. All rights reserved.
* See COPYING.txt for license details.
*/
?>
<div class="admin__field admin__field-option order-save-in-address-book">
    <input 
        name="<?= $block->escapeHtmlAttr($block->getForm()->getHtmlNamePrefix()) ?>[save_in_address_book]" 
        type="checkbox" 
        id="<?= $block->escapeHtmlAttr($block->getForm()->getHtmlIdPrefix()) ?>save_in_address_book" 
        value="0"<?php if (!$block->getDontSaveInAddressBook()) : ?> <?php endif; ?> 
        class="admin__control-checkbox"/>
    <label 
        for="<?= $block->escapeHtmlAttr($block->getForm()->getHtmlIdPrefix()) ?>save_in_address_book"
        class="admin__field-label"><?= $block->escapeHtml(__('Save in address book')) ?>
    </label>
</div>